language: python
python:
    - 2.6
    - 2.7
before_install:
	- sudo apt-get update
	- sudo apt-get install postgresql-9.1-postgis
install:
	- pip install -r API/feowl-api/requirements.txt --use-mirrors
before_script:
	- createdb -E UTF8 -U postgres template_postgis
	- createlang -d template_postgis plpgsql; 
	- psql -d template_postgis -c "CREATE EXTENSION hstore;" -U postgres 
	- psql -d template_postgis -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql -U postgres 
	- psql -d template_postgis -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql -U postgres 
	- psql -d template_postgis -c "select postgis_lib_version();" -U postgres 
	- psql -d template_postgis -c "GRANT ALL ON geometry_columns TO PUBLIC;" -U postgres 
	- psql -d template_postgis -c "GRANT ALL ON spatial_ref_sys TO PUBLIC;" -U postgres 
	- psql -d template_postgis -c "GRANT ALL ON geography_columns TO PUBLIC;" -U postgres
	- psql -c 'UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template_postgis';' -U postgres
	- psql -c 'create database feowl;' -U postgres
script:
	- python API/feowl-api/manage.py syncdb
	- python API/feowl-api/manage.py test